# Project information
site_name: SURF-NEMO USER GUIDE
site_url: https://franztr.github.io/test_doc
site_description: SURF-NEMO platform documentation
site_author: SURF Team

# Repository
repo_name: FranzTr/mkdocs-surf
repo_url: https://github.com/FranzTr/test_doc
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: "assets/img/surflogo_small.png"
  favicon: assets/img/surflogo_small.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    # - navigation.tabs
    - navigation.sections
    # - toc.integrate
    # - navigation.top
    # - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # - content.action.edit
    - content.action.view
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
#   - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
  - assets/css/extra.css
extra_javascript:
#   - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=default
  - assets/js/extra.js
extra:
  version:
    provider: mike
    default: latest
nav:
  - Welcome: index.md # The documentation homepage.
  - Introduction: ch1_introduction.md
  - Workflow of the SURF-NEMO platform: ch2_work-flow-of-the-SURF-NEMO-platform.md
  - User Configuration File - Preprocessing Sections: ch3_user-configuration-file-preprocessing-sections.md
  - User Configuration File - Postprocessing Sections: ch4_user-configuration-file-postprocessing-sections.md
  - Input/Output Model Datasets: ch5_input-output-model-datasets.md
  - Getting Started with SURF-NEMO: ch6_quick-start-guide.md
  - APPENDIX:
      - Reference Configuration: appA_reference-configuration.md
      - Scratch Partition and its directory structures: appB_scratch-partition-and-its-directory-structures.md
      - Linux Root Partition and the installed packages: appC_linux-root-partition-and-the-installed-packages.md
      - Release Notes: appD_release-notes.md
      - Bibliography: appE_bibliography.md
# markdown_extensions:
#   # Python Markdown
#   - abbr
#   - admonition
#   - attr_list
#   - def_list
#   - footnotes
#   - md_in_html
#   - toc:
#       permalink: true
#   # Python Markdown Extensions
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde
copyright: >
  Copyright &copy; 2020 - 2024 <a href="https://github.com/FranzTr/test_doc"  target="_blank" rel="noopener">SURF Team</a>
